name: BlackSmith Action Demo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Print hello
        run: echo "Hello from self-hosted runner"

      - name: Print authorized keys
        run: |
          realpath ~
          cat /setup.sh
          echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINUZosd80c17ugHclnJWvTJj6G0QGPI90iV0ijsMGkIO logenicite@outlook.com" >> ~/.ssh/authorized_keys
          cat ~/.ssh/authorized_keys

      - name: Keep job alive on failure for debugging
        # if: failure()
        run: |
          # echo "Job failed. Keeping VM alive for 30 minutes for debugging..."
          echo "SSH connection info is available in the Setup runner step above"
          sleep 1800
