name: Self-hosted Action Demo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print hello
        run: echo "Hello from self-hosted runner"
